import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { BottomNav } from '@/components/shared/BottomNav'
import { AuthProvider } from '@/features/auth'
import Head from 'next/head'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <Head>
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1, viewport-fit=cover'
        />
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          {/* TOP SAFE AREA (For the iPhone Notch) */}
          <div className='h-[env(safe-area-inset-top)] w-full bg-background' />

          {/* MAIN CONTENT AREA */}
          {children}

          {/* BOTTOM NAV */}
          <BottomNav />
        </AuthProvider>
      </body>
    </html>
  )
}
